apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: log-elastic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:7.17.3
          ports:
            - containerPort: 5601
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "https://elasticsearch-master:9200"
            - name: ELASTICSEARCH_USERNAME
              value: "kibana_system"
            - name: ELASTICSEARCH_PASSWORD
              value: "KAF8L4cElVT8GTgd"
            - name: ELASTICSEARCH_SSL_VERIFICATIONMODE
              value: "none"
            - name: SERVER_PUBLICBASEURL
              value: "http://kibana.35.207.106.1.nip.io"
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"